version: "3"
services:
    website:
        container_name: blogwatcher
        image: blogwatcher
        environment:
            - VIRTUAL_HOST=watch.0x8.host
            - LETSENCRYPT_HOST=watch.0x8.host
            - LETSENCRYPT_EMAIL=warburtonroland@gmail.com
            - VIRTUAL_PORT=3000
            - VIRTUAL_NETWORK=proxy-network
        volumes:
            - ./content:/usr/src/app/content

    mongo:
        container_name: mongo
        image: mongo
        environment:
            # back up admin user in case something goes wrong
            - MONGO_INITDB_DATABASE=imageHost
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=rhinos
        volumes:
            # For the startup script that mongo runs to create a new user
            - ./app/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            # Store the mongo database on the host to make it persistent between container restarts
            - ./mongo-volume:/data/db
        ports:
            - "27017:27017"
        expose:
            - 27017
        command: mongod --auth --quiet
        logging:
            driver: none

networks:
    default:
        external:
            name: nginx-proxy
